- name: install nginx and run nginx
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    anisible.builtin.yum:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started    